### PR TITLE
Implement simple two-sided chat system

### PR DESCRIPTION
**Pull request by Cepe6**

### CODE REVIEW

**Comment by mmitropolitsky** [comment]
Име и номер?

**Comment by mmitropolitsky** [comment]
Кодът изглежда добре.

**Comment by Cepe6** [comment]
Владимир Младенов, 6

**Comment by Cepe6** [comment]
Ignore https://github.com/mmitropolitsky/elsys_ip_2018/pull/4/commits/1688c555586bb79c061379cc0263b317332b2f67

**Pull request closed without merging**
